### ISSUE TITLE
filter/reduce on git concestor

### ISSUE THREAD

**Issue by tomdavidson** [folke/ultra-runner#100]
Thank you for Ultra Runner! I think a powerful feature would be to further filter based on files changed as per git history. One case would be preintegration cicd. Take `ultra -r --filter "apps/* build` which would build all the apps, whereas this feature,  --filter `ultra -r --filter "apps/* --filter concestor build` would only build the apps that have files that have changed since branching.

Git does all the work and Ultra Runner already depends on git, this feature would provide the UI wrapper, options in the config file, intersection of multiple filters, etc.  Here is a[ rather dated bash script](https://gist.github.com/tomdavidson/c1287055631fbac87023d7dad9868d5a) I have used in the past for a real world use case and the suggested git usage (`git merge-base --fork-point $left_ref $right_ref` is the star).

**Comment by tomdavidson** [comment]
@folke is this a feature you would accept a pr for? Implementation guidance for a contributor?

**Comment by folke** [comment]
Sorry for the late reply on this!

Could you clarify on how this would improve on the existing checks on whether a build needs to happen or not?

In your example, apps that have not changed since branching would not be built anyway?

**Comment by tomdavidson** [comment]
Hello @folke 

This feature would make it so we dont have work on everything in a mono repo, but only the things that are different tin the proposed merge. 

For example, say my repo has a handful of Cloud Run apps(we use Pulumi/TypeScript for our IAC). Via `ultra -r --filter "apps/* --filter concestor build`  I only build apps/* that are different in my branch when compared to `main` (in the get merge-base, left defaults to the repo default branch and right defaults to the current branch). I still get lots concurrency with `ultra` but I am not building and pushing every docker image in the repo - just the ones where something has changed.
