### ISSUE TITLE
run command in just one package + its descendants 

### ISSUE THREAD

**Issue by natew** [folke/ultra-runner#102]
Basically I have monorepo:

```
apps/*
packages/*
```

I want to build one app and only the packages it relies on, is that possible now? Would be nice for docker builds to reduce total build time.

**Comment by folke** [comment]
It is! I actually added this functionality a couple of weeks ago.

You can use `--filter` to select the packag(es) you need and then prefix the filter with `+` to include it's dependencies.

See https://github.com/folke/ultra-runner/blob/master/README.md#palm_tree-recursive-execution for more information.

Hope this helps.

**Comment by folke** [comment]
It would probably make sense to make this the default behavior though 🤔
