### ISSUE TITLE
[Question] Execute yarn commands concurrently

### ISSUE THREAD

**Issue by BeyondEvil** [folke/ultra-runner#105]
I'm terribly sorry if this is a stupid question, but I don't know how to get `ultra-runner` to "hijack" (your words) the `yarn workspaces` and run the command(s) concurrently?

Root directory `package.json` contains:
```json
{
  "private": true,
  "workspaces": [
    "yarns/**"
  ],
  "scripts": {
    "lint": "yarn workspaces run lint"
  },
  "ultra": {
    "concurrent": ["lint"]
  },
  "devDependencies": {
    "ultra-runner": "^3.5.0",
    **snip**   
  }
}
```

In one of the projects, the `package.json` contains:
```json
{
  "name": "worker",
  "version": "1.0.0",
  "description": "Worker for API",
  "main": "main.js",
  "engines": {
    "node": "10.x"
  },
  "scripts": {
    "build": "tsc",
    "test": "jest --runInBand --config ../../../jest.config.js",
    "lint": "eslint --ignore-path ../../../.eslintignore \"**/*.{ts,js}\""
  },
  "dependencies": {
    **snip**
  }
}
```

I've tried running `npx ultra lint` which does **not** run the linting concurrently

I've tried running `npx ultra yarn workspaces run lint` which does **not** run the linting concurrently

What am I doing wrong? 🙈 

I should mention when running `npx ultra -r npm run lint`, but then it's not really using `yarn workspaces`, is it? 🤔

**Comment by folke** [comment]
`npx ultra -r lint` is what you want.

You don't need to specify the "concurrent" part in the root package.json. That's only needed to make scripts within a single package **also** run concurrently.

Running script recursively (in this case, using your yarn workspaces config), always runs concurrently.

I hope this helps!

**Comment by BeyondEvil** [comment]
It does, thank you! 🙏
