### ISSUE TITLE
Cleanup command after sending a SIGINT

### ISSUE THREAD

**Issue by jgoux** [folke/ultra-runner#114]
Hello,

Thanks for this awesome runner! 🏃 

I'm using it to run all my workspace's `dev` script in parallel, it's so good!

One of my workspace is using a `docker-compose up` in its `dev` script and I'm looking for a way to execute a cleanup command after I do a `CTRL + C` in my terminal.

What signal do you send to the underlying scripts when quitting the terminal?

My use case is to be able to run a `docker-compose down` when I `CTRL + C` on ultra-runner. 😄

**Comment by folke** [comment]
That would be the `SIGTERM` signal :)
