### ISSUE TITLE
asterisk

### ISSUE THREAD

**Issue by tujoworker** [folke/ultra-runner#116]
Thanks for making this nice runner tool!

In my yarn workspace I have defined many local dependencies with an asterisk as the version (*)
But now, ultra thinks that these "version" have changed every time I run the same command again, these dependencies come in as "changed files". Something I do wrong?

**Comment by folke** [comment]
If it comes in as a `change` then it means that the dependency itself was rebuilt.

Would it be possible to post the exact command you do and the *redacted* output containing the changes?
