### ISSUE TITLE
expect can setting exclude some file in .ultra.cache.json

### ISSUE THREAD

**Issue by ctwowt** [folke/ultra-runner#117]
First, `ultra-runner` is awesome!!!
 
But, there is a using case: 

some build process can async produce files or expect exclude .gitignore don't put in .ultra.cache.json

``` 
async getFiles(directory: string, exclude: string[] = []): Promise<GitFiles> {
    ...
}

async function getPackageFiles(
  root: string,
  workspace: Workspace | undefined
): Promise<PackageFiles> {
  return {
    files: await cache.getFiles(root),
    deps: getDependencies(root, workspace),
  }
}
```

**Comment by folke** [comment]
I don't fully understand what you mean. Can you give an example of what you want to achieve?

**Comment by ShauniArima** [comment]
Maybe @ctwowt talk about files that are ignored in the `.gitignore` file but tracked in `.ultra.cache.json`. This is the case for build files.
