### ISSUE TITLE
asterisk application system

### ISSUE THREAD

**Issue by giulio68** [folke/ultra-runner#121]
hi to all, I installed the voip asterisk switchboard on raspberrypi 3+ and it works fine, now I would have thought of activating the gpio by making a call to an internal number, then run a shell command from the dialplan, created the virtual extension 100 I'm going to create a dialplan in the exstension_custom.conf file like so:  
[from-internal-custom]

exten => 100,1,answer()
exten => 100,n,wait (3)
exten => 100,n,system(/root/my folder/my file)
exten =>100,n.Hangup()

my file is an executable written in bash, and I can run it both from root @ raspberrypi, and from the asterisk CLI, but it doesn't work when I call the virtual extension, where do I make the mistake? can someone help me?

**Comment by folke** [comment]
I'm sorry, but `ultra-runner` has nothing to do with the asterisk switchboard.
