### ISSUE TITLE
Prefix logged lines with package name when using `--raw`

### ISSUE THREAD

**Issue by remorses** [folke/ultra-runner#160]
I am using the `--raw` option to not have the logs being cut when running in CI, the problem is that i can't really know from what package the logs come from

It would be cool to have the logged lines being prefixed with the package name, like this

```
> ultra -r --raw build

[package-1] ./src/index.ts → lib, lib...
[package-1] babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, read [package-1] more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers

[another-package] ./src/index.ts → lib, lib...
[another-package] babelHelpers: 'bundled' option was used by default. It is recommended to configure this option explicitly, [another-package] read more here: https://github.com/rollup/plugins/tree/master/packages/babel#babelhelpers
[another-package] created lib, lib in 501ms
```

I can work on a PR for this

**Comment by folke** [comment]
Have you tried to use `ultra --no-pretty build` instead?

Also, the interactive output only cuts logs while it's still running. Once ultra finishes, the full log is flushed to the output.

**Comment by remorses** [comment]
Thank you, `--no-pretty` is exactly what i wanted
