### ISSUE TITLE
Builds never cached if there is a dep on a build-less dep

### ISSUE THREAD

**Issue by hipstersmoothie** [folke/ultra-runner#163]
I have two packages `@packages/a` and  `@packages/b`.  `@packages/a` has no build step and  `@packages/b` has a build step. `@packages/b` depends on `@packages/a`

When I run `yarn ultra -r --filter "@packages/b" --build build` the cache is never hit and it does a full rebuild. I'm guessing this is because `@packages/a` has no build, it gets no cache file, and `ultra-runner` thinks it needs to build it again.

**Comment by hipstersmoothie** [comment]
Adding an empty build step fixes the problem, creating a cache for the buildless dep

```json
{
  "scripts": {
    "build": "echo nope"
  }
}
```

**Comment by thekip** [comment]
empty script would be enough: 
```
{
  "scripts": {
    "build": ""
  }
}
``

**Comment by thekip** [comment]
Duplicate https://github.com/folke/ultra-runner/issues/115

**Comment by hipstersmoothie** [comment]
Closing since it's a dupe
