### ISSUE TITLE
Concurrency without build still seems to do a topological sort

### ISSUE THREAD

**Issue by natew** [folke/ultra-runner#172]
I'd expect this:

```
ultra --silent -r --no-pretty --rebuild --concurrency 100 build
```

If I had 100 packages, would show 100 "build" commands straight away, and then the outputs would all follow. Instead, I see what looks like a topological build still happening. Note I'm not using `--build` which I know is topological, I'm trying to avoid that in this case but can't seem to.

**Comment by folke** [comment]
`--rebuild` sets the `--build` flag internally.
You need to add the `--no-topology` flag to skip topological checks
