### ISSUE TITLE
Webpack alternative?

### ISSUE THREAD

**Issue by yellow1912** [folke/ultra-runner#27]
Does it and can it replace webpack? I have a project that normally take 2mins just to build on webpack even though the end build is just a bit over 1mb. That makes Dev process super slow.

**Comment by folke** [comment]
Ultra is not a bundler, so this can't replace webpack.

Apart from that, ultra would be very useful when you would have multiple packages you need to build in a monorepo with webpack, since all builds could be done concurrently.
