### ISSUE TITLE
posttest runs before test is finished

### ISSUE THREAD

**Issue by manwithafox** [folke/ultra-runner#45]
I have seen that my ```posttest``` script is started before ```test``` has finished.

```test``` contains two subtasks that can run in parallel. So I have added ```test``` to ```ultra.concurrent```. ```posttest``` contains only one task and thus I have not tagged it as concurrent.

What leads to this behaviour and can I control it?  

Thanks

**Comment by folke** [comment]
I think I know what's happening here. I'll look into this!

**Comment by folke** [comment]
Fixed in [2.3.6](https://www.npmjs.com/package/ultra-runner)!

Let me know if you still have any issues.

**Comment by manwithafox** [comment]
Now everything is fine.
Thanks again for the quick fix.
