### ISSUE TITLE
how are dependencies determined?

### ISSUE THREAD

**Issue by tomdavidson** [folke/ultra-runner#48]
Hello, can you explain more how dependencies are determined? Is it based on lerna symbolic links? or scoped packages in the package.json dependencies object?

**Comment by folke** [comment]
Good question!

Dependencies between packages in a workspace are based on package.json only.
`ultra` doesn't really care on the underlying mechanism that was used to properly link those dependencies. That's the job of Lerna, Yarn Workspaces, Pnpm, ...

Internally, the dependencies within a workspace are modeled as a directed acyclic graph to determine the build order and concurrency.

Let me know if you want to know anything else

**Comment by tomdavidson** [comment]
Thanks @folke 
So if I have lerna, then Im stuck with lerna's symbolic links rather than the semver'd dependencies. With ultra's graph, I shouldn't need lerna's filtering (such as run test on dependents), so Ill have to look to see what yarn workspaces and ultra can do for my use. Will still need something similar to `lerna changed`.

The use case driving this question is decoupling the lifecycles of in-scope components from each other. If the mono-repo uses symlink based imports and not semver’d artifacts or semver’d git tags, then I can not update a component to a new breaking version without forcing all the dependents to change the at the same time. When dependency is on a semver’d package then there is no problem, it's just dependency management, but when those dependents depend on the HEAD of the integration branch the lifecycles ends up tightly coupled.

**Comment by folke** [comment]
ok, feel free to add a feature request for ultra!
