### ISSUE TITLE
`Runner.runRecursive` don't work with async/await as expected

### ISSUE THREAD

**Issue by shimarulin** [folke/ultra-runner#57]
I try to use `Runner` API to create tasks queue, but `runRecursive` don't work with async/await as expected, because it doesn't return a promise and `await` just skipped.

**Comment by shimarulin** [comment]
I open the PR #56 to fix it

**Comment by folke** [comment]
I've just merged your PR and added an additional fixe related to using the API:
* all process.exit calls have been moved to cli.ts. The API simply throws any errors like you would expect

I'm currently waiting for Github Actions to complete and will push a new release after that.

Thanks again for fixing this!

**Comment by folke** [comment]
v3.2.1 has just been released with your fix! 🚀
