### ISSUE TITLE
Does ultra-runner work with git submodules?

### ISSUE THREAD

**Issue by trusktr** [folke/ultra-runner#59]
Both Lerna and Rush.js are not able to track changes in projects/packages if they are git submodules.

For various reasons, I'd like for some (or all) packages in my monorepo (actually I call it "umbrella repo" because it isn't a single repo) to be git submodules.

Rush.js totally fails running _anything_ when git submodules are present in the umbrella repo.

Lerna allows me to run commands across all git submodules just fine. For example, `lerna run build` is able to run commands in a certain order depending on the dependency tree between packages.

However, things like `lerna version` or `lerna publish` don't work, because Lerna does not know how to determine if a package is modified if it is a git submodule.

I think the solution would be for Lerna to go into the submodule, and run `git status` (or whatever) inside the submodule to detect if it has changed. Or perhaps Lerna needs to identify submodule commit hash changes in `git diff` output at the top level. So due to lack of support for detecting changes of git submodules, Lerna isn't able to determine what packages changed (`lerna changed`). It just simply thinks that everything is always changed.

Does ultra-runner support git submodules? If not, could that be something to be considered as an addition to ultra-runner?

**Comment by folke** [comment]
The way `ultra` currently detects file changes, I'd say it probably also wouldn't detect changes in submodules.

I'll have a look into this tomorrow and will add support for git submodules in case it wouldn't work as expected.

Thanks!

**Comment by folke** [comment]
I further looked into this and it actually already works as expected :)

There was already functionality in there that checks for file changes related to the correct git repository associated with the relevant package. This means the submodule use-case is supported as is.

To be 100% sure, I also ran some tests and it all works as expected.

In case you're seeing issues anyway, feel free to reopen this issue.
