### ISSUE TITLE
Running postinstall using ultra

### ISSUE THREAD

**Issue by fahrradflucht** [folke/ultra-runner#60]
Hey 👋 First of all, thanks for building this, it looks super nice.

We have a repository where a bunch of stuff is happening in the `postinstall` hook. The imagined workflow is, that people checkout a branch, run `yarn` and everything works.

It would be super nice, if there would be an easy way for me to run these postinstall hooks in an ultra-context, using its concurrency features and console ui. I'm unsure what would be the best approach though. Maybe something like `ultra install`?

**Comment by folke** [comment]
Hi!

The easiest way to make this work, is to rename your real `postinstall` hook to something else, like `afterinstall` and then run it through `ultra` in postinstall:

```javascript
{
  "scripts": {
    "postinstall": "npx ultra ultrainstall",
    "ultrainstall": "do here whatever you had in postinstall"
  },
  "ultra": {
    "concurrent": [
      "ultrainstall"
    ]
  }
}
```

I hope this helps!
