### ISSUE TITLE
Large git repos are not supported

### ISSUE THREAD

**Issue by QuestionAndAnswer** [folke/ultra-runner#66]
I've tried to launch build for lerna repo with huge git repo, which led to this issue. I've just added additional line in cli.js directly in node_modules to see full error with stack trace, as it was hidden, at here is what I found.

`
error stdout maxBuffer length exceeded
{ RangeError [ERR_CHILD_PROCESS_STDIO_MAXBUFFER]: stdout maxBuffer length exceeded
    at Socket.onChildStdout (child_process.js:354:14)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:265:13)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:94:17)
  cmd: 'git ls-files --full-name -s -d -c -m -o --directory -t' }
`

Running this command standalone indeed returns huge lists, which I waited few minutes to until stopped it.

Is it possible to bypass this step or increase buffer limit for such cases?

**Comment by QuestionAndAnswer** [comment]
rebuild command also not working and returning the same result.

**Comment by folke** [comment]
There's actually a hidden `--debug` switch, but of course you couldn't have known :)

I'll have a look to see what I can do.

Thank you for reporting!

**Comment by folke** [comment]
I've increased the buffer size to 1GB. It used to be only 1MB, which is indeed pretty small.

I'll release a new build once Github Actions pass.

**Comment by folke** [comment]
v3.2.2 has been released containing the fix.

Feel free to reopen this issue if you'd still have problems!

**Comment by QuestionAndAnswer** [comment]
Thanks!
