### ISSUE TITLE
Recursive pattern exclusion

### ISSUE THREAD

**Issue by zekth** [folke/ultra-runner#72]
The recursive option may need an exception option for the folder pattern. Because it looks recursively for the `package.json` file even in dist folders, causing issues. For example:
```
# Raw environment
- packages
-- api
--- package.json
-- ui
--- package.json
package.json
```
So i have my `build` task which will run `build` in each subfolder. The API compiles and copy it's package.json to be installed for the nodejs server. Which ends up in:
```
# Already built environment
- packages
-- api
--- dist
---- package.json
--- package.json
-- ui
--- dist
--- package.json
package.json
```
And if i run `npx ultra build` again it ends up using the `package.json` of the `packages/api/dist` which breaks the build process. A solution would be to set a command like:
```
    "build": "rm -rf packages/*/dist && npx ultra -r yarn build",
```

A solution would be to check on `.gitignore` maybe. Any idea?

**Comment by folke** [comment]
Thank you for reporting this. Related to #70 

The work-around in your case would be to specify the package regexes to use with the Yarn workspaces syntax for example.

To do this, you need to add the following to your top-level package.json:
```json
"workspaces": [
    "packages/*"
  ]
```

---

Apart from the quick-fix I'll see for a better solution where you can configure exclusions and possible inclusions for projects specifically for `ultra`

**Comment by folke** [comment]
Will be fixed by #74

**Comment by folke** [comment]
Closing in favor of #74

**Comment by zekth** [comment]
Solution is:
```
  "workspaces": [
    "packages/!(dist)"
  ]
```

Thanks

**Comment by folke** [comment]
Right! That definitely also works.
