### ISSUE TITLE
Package ignore glob patterns should be configurable

### ISSUE THREAD

**Issue by folke** [folke/ultra-runner#74]
Right now, we have a default ignore list of regexes for package exclusions:
```js
const DEFAULT_IGNORE = [
  "**/node_modules/**",
  "**/bower_components/**",
  "**/test/**",
  "**/tests/**",
  "**/__tests__/**",
]
```

Might be a good idea to integrate [CosmiConfig](https://github.com/davidtheclark/cosmiconfig) and make parts of `ultra` configurable, including the regex above.

**Comment by zekth** [comment]
Just a quick note, those are `glob` patterns and not `regex`. If you want to use Glob and regex at the same time you need to use a combo of https://github.com/micromatch/is-glob and https://github.com/terkelg/globrex . But as long as most of the tooling are using Glob patterns i'd stick to it.

**Comment by folke** [comment]
@zekth yeah, I meant glob patterns, but thanks for pointing that out. My bad :)

**Comment by folke** [comment]
Closing in favor of #85
