### ISSUE TITLE
Ultra cache could be used for more than builds (ie. lint)

### ISSUE THREAD

**Issue by RDeluxe** [folke/ultra-runner#76]
It would be nice to be able to leverage ultra cache system for linting. I don't know if this could be an cli option ?

Thanks for your work, I'm investigating ultra to see if we should migrate from Rush to ultra+pnpm workspaces :)

**Comment by folke** [comment]
It actually already has an option for this :)

You can use the `--build` flag with whatever action and it will use the cache etc.

So in your case:

```bash
$ ultra -r --build lint
...
```

**Comment by folke** [comment]
However, the cache is not dependent on the action you perform, so that should probably change...

**Comment by RDeluxe** [comment]
Hi !

My thoughts :

- `--build` is using the dependency tree, which I don't need for lint tasks (I want as many in // as possible)
- `--build` is, well, named in a way which does not encourage its usage for other tasks
- As you noted, cache should probably be created "by task/script" if not a lint task may not be re-triggered because a previous build task finished on the same source code, and vice-versa

**Comment by folke** [comment]
Makes sense. I was planning to do some refactoring on the runner code. Will see if I can include this then. Thanks!

**Comment by folke** [comment]
I'll add this at some point in the future. Sorry for the delay!
