### ISSUE TITLE
Prefix output for `--no-pretty` with the package name

### ISSUE THREAD

**Issue by folke** [folke/ultra-runner#90]
Right now, `--no-pretty` while mix output from all running commands and prefix them with the command.

It would be better to also add the package name to the prefix to make it easier to debug what output is coming from what command.

(see also #89)

**Comment by folke** [comment]
Fixed in v3.4.1 🚀

**Comment by folke** [comment]
That's really odd.

Are you sure you're running the latest version of ultra? Should be 3.4.1 or higher.

Example output in one of my repos:
```shell
$ ultra -r --no-pretty --filter "apps/*" "echo test"
```
```
❯ @splora/api at apps/api (@splora/api)
❯ @splora/app at apps/app (@splora/app)
$ echo test (@splora/api)
$ echo test (@splora/app)
[@splora/api::echo] test
[@splora/app::echo] test
```

The first two lines are titles, then twice a command that will be executed, followed by the ouput.

Packages in this example are `@splora/api` and `@splora/app`

**Comment by folke** [comment]
Package names are only added when running with `-r`, so when running in a single package. Maybe that's the issue?

**Comment by tshelburne** [comment]
You are correct, version problem. I updated the package.json in a different branch.

Thanks!

**Comment by folke** [comment]
Great, glad you figured it out!
