### ISSUE TITLE
Feature request: extended glob for --filter

### ISSUE THREAD

**Issue by lettertwo** [folke/ultra-runner#91]
In a yarn workspace setup, it would be nice to be able to target multiple, specific packages using [extended globbing](https://www.linuxjournal.com/content/bash-extended-globbing):

```shell
$ ultra -r --filter "@scope/(app|docs)" pwd
```

It is currently possible to use the `--filter` option to target a specific package:
```shell
$ ultra -r --filter "@scope/app" pwd
```

Or all packages under a scope or directory:
 ```shell
$ ultra -r --filter "@scope/*" pwd
```

Assuming this is a useful feature, maybe it would be as simple as [adding config](https://www.npmjs.com/package/globrex#optionsextended) for globrex [here](https://github.com/folke/ultra-runner/blob/72a19e678f71a5e4275d293913a91ae16018fb4a/src/workspace.ts#L126)?

**Comment by folke** [comment]
Added in v3.5.0!

The extended syntax is a bit different than in your example. You need to prefix the `(app|docs)` with a `+` as in:

```shell
$ ultra -r --filter "@scope/+(app|docs)" pwd
```
