### ISSUE TITLE
test.svg in README is maxing out CPU in Chrome

### ISSUE THREAD

**Issue by eezing** [folke/ultra-runner#92]
Noticed my fans were winding up while viewing the README. A quick & dirty test with the SVG in full view, with 1 open tab in Chrome on 3.5 GHz Dual-Core i7 Macbook Pro:

![Screen Shot 2020-05-20 at 2 25 58 PM](https://user-images.githubusercontent.com/6968110/82499260-39037d00-9aa6-11ea-9fdf-f35c7d894eb5.png)

**Comment by folke** [comment]
I noticed as well. Will see to change it by an animated GIF instead.

**Comment by folke** [comment]
Fixed in https://github.com/folke/ultra-runner/commit/f3860c26d5e4d75819200ddd19f3646eda875cdd

Sorry for the delay!
