### ISSUE TITLE
Sensitive information may have been inadvertently committed to the repository

### ISSUE THREAD

**Issue by RA80533** [folke/ultra-runner#97]
The information in question resides in [.vsgitbuild](https://github.com/folke/ultra-runner/blob/e68c314fa20f9a5548e6b37031362b2e094c089f/.vsgitbuild), located at the root of the repository. I suggest you revoke the exposed personal API token (see [this blog post](https://github.blog/2013-05-16-personal-api-tokens/)), modify the root .gitignore file to exclude .vsgitbuild from the repository, and push your repository after running `git rm --cached .vsgitbuild`.

**Comment by folke** [comment]
Thank you for pointing this out!!
The token in question only had read access on notification count, but still a pretty bad thing I overlooked there.

I must've added this by accident.

Thanks again!
